### ISSUE TITLE
Game time slows down

### ISSUE THREAD

**Issue by JarLowrey** [JarLowrey/Space-Shooter-Android#24]
As levels are played in a row, the game time slows down. Does not relate to the number of enemies on screen, rather how many levels have ran in a row. Can be sped up again by killing the app in the task manager and restarting the app.

**Comment by JTronLabs** [comment]
Discovered the issue. In the game loop, updating can take longer than is allowed currently. So, with the present fixed 40fps rendering should occur every 25ms, but the game loop can take over 50ms! Also, the soonest the loop will be re-posted to the Handler is 5ms. So the more images/complexity/actions going onscreen at once will slow the game loop/engine down considerably. 

I imagine this can be fixed by separating the rendering and physics loops. Allow the game to render as fast as hardware can allow, but continue to update the physics separately every "game tick" (prob will use 60 times/sec). Thus, if frames are skipped the physics will be maintained and only the display will be more choppy.

Nice pseudo-code here:
http://gamedev.stackexchange.com/questions/75558/frameskipping-in-android-gameloop-causing-choppy-sprites-open-gl-es-2-0

**Comment by JTronLabs** [comment]
Fixed! Now the game gets a little laggy (skipped frames) under heavy load, but the physics do not change.
